import { useEffect, useRef, useState } from "react"
import { SharedWebGLBlurCanvas, SharedWebGLBlurImage } from "./web-gl-blue-img"

const works = [
  {
    title: "Project 05",
    year: "2026",
    imageSrc: "/2026.png",
    description: "The latest personal landing page",
  },
  {
    title: "Project 04",
    year: "2025",
    imageSrc: "/2025.png",
    description: "The first personal website generated by Claude Code",
  },
  {
    title: "Project 03",
    year: "2024",
    imageSrc: "/2024.png",
    description: "I have been continuously improving my personal website.",
  },
  {
    title: "Project 02",
    year: "2023",
    imageSrc: "/2023.png",
    description: "I am not satisfied with the first version of the website.",
  },
  {
    title: "Project 01",
    year: "2022",
    imageSrc: "/2022.png",
    description: "My first website when I was learning front-end development.",
  },
]

function getScrollParent(element: HTMLElement | null) {
  let parent = element?.parentElement

  while (parent) {
    const style = window.getComputedStyle(parent)
    const overflowY = style.overflowY

    if (overflowY === "auto" || overflowY === "scroll") {
      return parent
    }

    parent = parent.parentElement
  }

  return null
}

export function SectionFour() {
  const sectionRef = useRef<HTMLElement | null>(null)
  const stageRef = useRef<HTMLDivElement | null>(null)
  const trackRef = useRef<HTMLDivElement | null>(null)
  const rafRef = useRef<number | null>(null)

  const maxShiftRef = useRef(0)

  const [isDesktop, setIsDesktop] = useState<boolean | null>(null)

  useEffect(() => {
    const media = window.matchMedia("(min-width: 768px)")

    const updateDesktop = () => {
      setIsDesktop(media.matches)
    }

    updateDesktop()
    media.addEventListener("change", updateDesktop)

    return () => {
      media.removeEventListener("change", updateDesktop)
    }
  }, [])

  useEffect(() => {
    const section = sectionRef.current
    const stage = stageRef.current
    const track = trackRef.current

    if (!section || !stage || !track) return

    if (!isDesktop) {
      track.style.transform = "translate3d(0, 0, 0)"
      return
    }

    const scrollParent = getScrollParent(section)

    if (!scrollParent) return

    const measure = () => {
      maxShiftRef.current = Math.max(0, track.scrollWidth - stage.clientWidth)
    }

    const update = () => {
      rafRef.current = null

      /*
        注意：
        SectionFour 组件本身在 FullScreenScroll 的 section 包装层里面。
        真正参与纵向滚动高度计算的是外层包装 section，
        所以这里优先取 parentElement。
      */
      const scrollSection = section.parentElement as HTMLElement | null
      if (!scrollSection) return

      const viewportHeight = scrollParent.clientHeight
      const scrollTop = scrollParent.scrollTop

      const start = scrollSection.offsetTop
      const end =
        scrollSection.offsetTop + scrollSection.offsetHeight - viewportHeight

      const rawProgress = end <= start ? 0 : (scrollTop - start) / (end - start)

      const progress = Math.min(1, Math.max(0, rawProgress))
      const translateX = -progress * maxShiftRef.current

      track.style.transform = `translate3d(${translateX}px, 0, 0)`
    }

    const requestUpdate = () => {
      if (rafRef.current !== null) return
      rafRef.current = window.requestAnimationFrame(update)
    }

    const handleResize = () => {
      measure()
      requestUpdate()
    }

    measure()
    update()

    scrollParent.addEventListener("scroll", requestUpdate, { passive: true })
    window.addEventListener("resize", handleResize)

    return () => {
      scrollParent.removeEventListener("scroll", requestUpdate)
      window.removeEventListener("resize", handleResize)

      if (rafRef.current !== null) {
        window.cancelAnimationFrame(rafRef.current)
      }
    }
  }, [isDesktop])

  return (
    <section
      ref={sectionRef}
      className="relative border-t border-b border-[#ff3f32]/55 bg-white"
      style={{
        height:
          isDesktop === true ? `${Math.max(works.length, 2) * 100}svh` : "auto",
      }}
    >
      {/* Desktop */}
      {isDesktop === true ? (
        <div className="sticky top-0 h-svh overflow-hidden bg-white">
          <main className="relative z-10 grid h-full grid-cols-[33%_1fr]">
            <div className="flex min-h-0 flex-col justify-between border-r border-[#ff3f32]/55 px-7 pt-8 pb-11">
              <div className="h-3 w-24 bg-[#ff3f32]" />

              <div className="text-[#ff3f32]">
                <p className="mb-6 text-sm font-black tracking-[0.22em] uppercase">
                  History
                </p>

                <h2 className="max-w-[7ch] text-[clamp(4.4rem,7vw,8.7rem)] leading-[0.9] font-black tracking-[-0.055em]">
                  Archive
                </h2>
              </div>

              <div className="text-[#ff3f32]">
                <p className="max-w-[13ch] text-[clamp(2rem,2.15vw,2.65rem)] leading-[1.12] font-medium tracking-[-0.05em]">
                  My personal homepage history from 2022 to 2026.
                </p>
              </div>
            </div>

            <SharedWebGLBlurCanvas
              containerRef={stageRef}
              className="relative flex min-w-0 items-center overflow-hidden"
            >
              <div
                ref={trackRef}
                className="flex h-full w-max items-center will-change-transform"
              >
                {works.map((work) => (
                  <div
                    key={work.title}
                    className="flex h-full flex-row items-center"
                  >
                    <div className="h-[calc(min(73svh,52vw)+2px)] w-10 border-t border-b border-[#ff3f32]/55"></div>
                    <div className="flex h-full items-center border-r border-l border-[#ff3f32]/55">
                      <article className="grid w-[min(58svh,42vw)] flex-none grid-rows-[1fr_auto] overflow-hidden border-t border-b border-[#ff3f32]/55 bg-white">
                        <div className="relative aspect-square overflow-hidden">
                          <SharedWebGLBlurImage
                            src={work.imageSrc}
                            alt={work.title}
                            className="h-full w-full cursor-zoom-in object-cover"
                            pixelSize={16}
                            blurStrength={3.5}
                            glassStrength={0.3}
                            noiseStrength={0.1}
                            noiseScale={520}
                            revealRadius={0.14}
                            revealSoftness={0.18}
                            objectFit="cover"
                          />
                        </div>

                        <div className="h-[min(15svh,10vw)] border-t border-[#ff3f32]/55 p-6 text-[#ff3f32]">
                          <div className="mb-4 flex items-center justify-between gap-6">
                            <h3 className="text-2xl font-black tracking-[-0.04em] uppercase">
                              {work.title}
                            </h3>

                            <span className="text-sm font-black tracking-[0.22em] uppercase">
                              {work.year}
                            </span>
                          </div>

                          <p className="max-w-[28ch] text-base leading-snug font-medium tracking-[-0.03em]">
                            {work.description}
                          </p>
                        </div>
                      </article>
                    </div>
                  </div>
                ))}
              </div>
            </SharedWebGLBlurCanvas>
          </main>
        </div>
      ) : null}

      {/* Mobile */}
      {isDesktop === false ? (
        <div className="bg-white">
          <div className="border-b border-[#ff3f32]/55 px-6 pt-7 pb-8 text-[#ff3f32]">
            <div className="mb-16 h-3 w-24 bg-[#ff3f32]" />

            <p className="mb-5 text-sm font-black tracking-[0.22em] uppercase">
              History
            </p>

            <h2 className="max-w-[7ch] text-[clamp(3.9rem,19vw,6rem)] leading-[0.9] font-black tracking-[-0.055em]">
              Archive
            </h2>

            <p className="mt-10 max-w-[18ch] text-[clamp(1.45rem,7vw,2.15rem)] leading-[1.12] font-medium tracking-[-0.05em]">
              My personal homepage history from 2022 to 2026.
            </p>
          </div>

          <SharedWebGLBlurCanvas className="relative bg-white">
            {works.map((work) => (
              <div key={work.title} className="flex flex-col">
                <div className="flex h-8 border-b border-[#ff3f32]/55">
                  <div className="w-6 border-r border-[#ff3f32]/55" />
                  <div className="flex-1" />
                  <div className="w-6 border-l border-[#ff3f32]/55" />
                </div>

                <div className="flex flex-row items-stretch">
                  <div className="w-6 flex-none border-r border-b border-[#ff3f32]/55" />

                  <article className="grid min-w-0 flex-1 grid-rows-[auto_auto] overflow-hidden border-b border-[#ff3f32]/55 bg-white text-[#ff3f32]">
                    <div className="relative aspect-square overflow-hidden">
                      <SharedWebGLBlurImage
                        src={work.imageSrc}
                        alt={work.title}
                        className="h-full w-full cursor-zoom-in object-cover"
                        pixelSize={16}
                        blurStrength={3.5}
                        glassStrength={0.3}
                        noiseStrength={0.1}
                        noiseScale={520}
                        revealRadius={0.14}
                        revealSoftness={0.18}
                        objectFit="cover"
                      />
                    </div>

                    <div className="border-t border-[#ff3f32]/55 px-6 py-6 text-[#ff3f32]">
                      <div className="mb-4 flex items-center justify-between gap-6">
                        <h3 className="text-2xl font-black tracking-[-0.04em] uppercase">
                          {work.title}
                        </h3>

                        <span className="text-sm font-black tracking-[0.22em] uppercase">
                          {work.year}
                        </span>
                      </div>

                      <p className="max-w-[28ch] text-base leading-snug font-medium tracking-[-0.03em]">
                        {work.description}
                      </p>
                    </div>
                  </article>

                  <div className="w-6 flex-none border-b border-l border-[#ff3f32]/55" />
                </div>
              </div>
            ))}
          </SharedWebGLBlurCanvas>
        </div>
      ) : null}
    </section>
  )
}
